set_property PACKAGE_PIN E3 [get_ports clk_100M]
set_property PACKAGE_PIN D10 [get_ports uart_tx]
set_property PACKAGE_PIN F6 [get_ports led0]
set_property PACKAGE_PIN D9 [get_ports {btn[0]}]
set_property PACKAGE_PIN C9 [get_ports {btn[1]}]
set_property PACKAGE_PIN B9 [get_ports {btn[2]}]
set_property PACKAGE_PIN B8 [get_ports {btn[3]}]
set_property PACKAGE_PIN A8 [get_ports {sw[0]}]
set_property PACKAGE_PIN C11 [get_ports {sw[1]}]
set_property PACKAGE_PIN C10 [get_ports {sw[2]}]
set_property PACKAGE_PIN A10 [get_ports {sw[3]}]

set_property IOSTANDARD LVCMOS33 [get_ports clk_100M]
set_property IOSTANDARD LVCMOS33 [get_ports uart_tx]
set_property IOSTANDARD LVCMOS33 [get_ports led0]
set_property IOSTANDARD LVCMOS33 [get_ports btn]
set_property IOSTANDARD LVCMOS33 [get_ports sw]